### 전체 Post 목록 조회 (페이징)
GET http://localhost:8081/posts?page=0&size=10
Accept: application/json

###

### 특정 Post 조회 (예: id 1인 경우)
GET http://localhost:8081/posts/1
Accept: application/json

###

### 새 Post 생성
POST http://localhost:8081/posts
Content-Type: application/json

{
  "title": "새로운 포스트 제목",
  "content": "이것은 포스트 내용입니다."
}

###

### Post 업데이트 (예: id 1번 포스트 제목 및 내용 수정)
PUT http://localhost:8081/posts/1
Content-Type: application/json

{
  "title": "수정된 포스트 제목",
  "content": "수정된 포스트 내용입니다."
}

###

### 특정 Post 삭제 (예: id 1인 경우)
DELETE http://localhost:8081/posts/1
Accept: application/json
