### Post Detail 조회 (postId: 1인 경우)
GET http://localhost:9090/post-details/1
Accept: application/json

###

### Post Detail2 조회 (CompletableFuture를 사용하는 메서드, postId: 1인 경우)
GET http://localhost:9090/post-details2/1
Accept: application/json
