### 전체 Todo 목록 조회
GET http://localhost:8080/todos
Accept: application/json


### proxy get todos

GET http://localhost:8080/todos-proxy
Accept: application/json

###

### 특정 Todo 조회 (예: id 1인 경우)
GET http://localhost:8080/todos/1
Accept: application/json

###

### 새 Todo 추가
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "운동하기",
  "done": false
}

###

### Todo 업데이트 (예: id 1번의 제목과 상태 수정)
PUT http://localhost:8080/todos
Content-Type: application/json

{
  "id": 1,
  "title": "운동하기 (수정됨)",
  "done": true
}

###

### Todo 삭제 (예: id 2번 삭제)
DELETE http://localhost:8080/todos/2
Accept: application/json
